// <auto-generated />
using System;
using LoanOfferer.Domain.Infrastructure.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoanOfferer.Domain.Infrastructure.Migrations
{
    [DbContext(typeof(LoanOfferContext))]
    [Migration("20190929115305_LoanOffererMigration")]
    partial class LoanOffererMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("LoanOfferer.Domain.Infrastructure.SQLite.LoanOfferDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress");

                    b.Property<int>("MaxLoanAmount");

                    b.Property<string>("Pesel");

                    b.Property<int>("RequestedLoanAmount");

                    b.HasKey("Id");

                    b.ToTable("LoanOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
